# Generated by Django 4.0.4 on 2022-06-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='date_receita',
            new_name='data_receita',
        ),
    ]
